---
title: "Michoacan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{michoacan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(electoral)
library(tidyverse)
#bd <- read_csv("~/Downloads/michoacan_municipal_2018_casilla.csv")
bd <- read_csv("~/Downloads/Presidencia_2018_casilla.csv")
bd <- filter(bd, NOMBRE_ESTADO=="MICHOACÁN")
bd <- rename(bd, "nombre_edo"="NOMBRE_ESTADO", "edo"="ESTADO")
info <- list()
partidos <- c("independiente_1","independiente_2")
coaliciones <- list(c("pan",  "prd","mc"),
                    c("pri", "pvem", "panal"),
                    c("pt","morena", "es")
)
color <- c("coalición_pan prd mc"="#2260BF",
           "coalición_pt morena es"="#BF3722",
           "coalición_pri pvem panal"="#23A95D", 
           "independiente_1"="grey", 
           "independiente_2"="purple3")
info <- electoral::preparar_info_de_eleccion(bd = bd,
                                  partidos = partidos,
                                  coaliciones = coaliciones,
                                  unidad_analisis = "nombre_edo",
                                  id_unidad_analisis="MICHOACÁN",
                                  año_analisis = 2018,
                                  nombre_unidad_analisis = "Elección presidencial-Michoacán",
                                  colores = color)


```
## Mapas



```{r}
library(sf)
library(leaflet)
secc <- st_read("~/Downloads/DISTRITO_FEDERAL.shp", stringsAsFactors = FALSE, quiet = TRUE) %>%
  st_transform(4326) 
graficar_fuerza_electoral(info, secc, analisis = "coalición_pt morena es",nivel="distrito", interactiva = T)

```
```{r}
secc <- st_read("~/Dropbox (Selva)/Ciencia de datos/Consultoría Estadística/Recursos/Externos/INE/SHP/2017/16 - Michoacán/SECCION.shp", stringsAsFactors = FALSE, quiet = TRUE) %>%
  st_transform(4326) 
graficar_fuerza_electoral(info, secc, analisis = "coalición_pt morena es",nivel="seccion", interactiva = T)

```

## Barras

```{r}
graficar_total_votacion(info)

```
```{r}
info_dis <- preparar_info_de_eleccion(bd = bd,
                                  partidos = partidos,
                                  coaliciones = coaliciones,
                                  unidad_analisis = "nombre_distrito",
                                  id_unidad_analisis="ZAMORA DE HIDALGO",
                                  año_analisis = 2018,
                                  nombre_unidad_analisis = "Elección presidencial- Zamora de Hidalgo",
                                  colores = color)
graficar_total_votacion(info_dis)

```




```{r}
info_secc <- preparar_info_de_eleccion(bd = bd,
                                  partidos = partidos,
                                  coaliciones = coaliciones,
                                  unidad_analisis = "seccion",
                                  id_unidad_analisis=411,
                                  año_analisis = 2018,
                                  nombre_unidad_analisis = "Elección presidencial- Sección 411",
                                  colores = color)
graficar_total_votacion(info_secc)

```
